services:
  redis:
    image: valkey/valkey:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  streamer:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      RUST_LOG: info
      STREAMER_SERVER_ADDRESS: http://localhost:8080
      STREAMER_REDIS_URL: redis://redis:6379
    env_file: api/.env
    depends_on:
      - redis

volumes:
  redis_data:
