services:
  redis:
    image: valkey/valkey:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # streamer:
  #   build:
  #     context: .
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     RUST_LOG: info
  #   env_file: server/.env
  #   depends_on:
  #     - redis

volumes:
  redis_data:
